### ISSUE TITLE
Support partial objects within arrays

### ISSUE THREAD

**Issue by jenimi** [ozkxr/match-json#11]
Very nice lib, I find it very useful, but I have some issues with the partials. For example the following cases:

```
partial([1, {"test": "aaa"}], [1, {}]))
partial([1, {"test": "aaa", "key2": 33}], [1, {"key2": 33}])
```
Currently both of them return false, while I would expect them to return true, as they partially match the objects in the array. 

Do you agree, or I am misinterpreting the `partial` usage? If you agree I can prepare a PR with some fixes?

**Comment by ozkxr** [comment]
Yes, you understand perfectly  `partial` usage; the object-inside-array case just flew over my head.
And yes, a PR would be welcome.

**Comment by ozkxr** [comment]
Well done, good fix. Nice revamp to the test code. Thank you! 😃

Edit: The version 1.3.3 with your changes is now published on npm.
