### ISSUE TITLE
v1.3.6 introducing unexpected changes

### ISSUE THREAD

**Issue by CYriuk** [ozkxr/match-json#24]
Hello 👋 
Trying to bump from v1.3.5 to v1.3.6 seems to break multiple tests in our company apps. 
🕵️‍♂️ The faulty change seems to be related to [this commit](https://github.com/ozkxr/match-json/commit/4da5785f7e3f1bb70fb8eaa1318d9fae6faeea7c). 
Adding the check to object[key] leads to checking if object[key] is truthy (not `null`, `undefined`, `false`, `0`, `""`, `NaN`, or an empty object/array).
Questions: What was the purpose of this change? How can we avoid returning false if, for example, both values are `null`?

**Comment by ozkxr** [comment]
Hello. Thanks for the heads up.

The commit was to fix an unintended behaviour[1] but I suspect the issue you describe is also unintended—a bug.

I will investigate further and provide a more robust solution.


In the mean time (let's say 1-2 days), can you stay on 1.3.5?

I appreciate both your feedback and your patience. 


[1]: Prior to that commit, when comparing objects, `match` just checked for both objects' array of keys to be the same length and assumed it had the same keys—a wrongful assumption.

**Comment by ozkxr** [comment]
Hello. Could you provide me a reproducible test just to make sure we are on the same page?

Thank you!

Edit: I think I now understand it.

this: `match({ a: false }, { a: false })` is broken. OK, I'll fix it.

**Comment by ozkxr** [comment]
Ready. Version `1.3.7` is now live on npm.

`match` now passes these test cases I just added:

```
// Falsy values

it("match:object_null_null_value_true", (t) =>
  expect(match({ a: null }, { a: null })).to.equal(true));

it("match:object_undefined_undefined_value_true", (t) =>
  expect(match({ a: undefined }, { a: undefined })).to.equal(true));

it("match:object_false_false_value_true", (t) =>
  expect(match({ a: false }, { a: false })).to.equal(true));

it("match:object_zero_zero_value_true", (t) =>
  expect(match({ a: 0 }, { a: 0 })).to.equal(true));

it("match:object_emptystring_emptystring_value_true", (t) =>
  expect(match({ a: "" }, { a: "" })).to.equal(true));

it("match:object_nan_nan_value_true", (t) =>
  expect(match({ a: NaN }, { a: NaN })).to.equal(false));

it("match:object_emptyobject_emptyobject_value_true", (t) =>
  expect(match({ a: {} }, { a: {} })).to.equal(true));

it("match:object_emptyarray_emptyarray_value_true", (t) =>
  expect(match({ a: [] }, { a: [] })).to.equal(true));
```

Note that `NaN` is not equal to `NaN` since that's the intended behavior built in the language.

--- 

I really appreciate your feedback and your patience

I hope this bug hasn't caused any major inconveniences.

If you find something else needs to be fixed, please don't hesitate in filing another issue or reopen this.

Thanks! 🚀

**Comment by CYriuk** [comment]
Hey @ozkxr late reply, thanks a lot for looking at this. I appreciate you taking the time to look and fix this.
We stayed on v1.3.5 in between and now we are on v1.3.7, the upgrade went super smoothly 🚀
