### ISSUE TITLE
Add support for `Number`, `String`, `Boolean` validators

### ISSUE THREAD

**Issue by Turbo87** [ozkxr/match-json#5]
It would be awesome if using `Number` as a validator corresponded to something like `value => typeof value === 'number'` or `value => value instanceof Number`, and similar for `String` and `Boolean`.

**Comment by ozkxr** [comment]
Hello. Is this what you want be able to do?

```
match(3.1415, isType('Number'))
match('a boring string', isType('String'))
match(true, isType('Boolean'))
```

I just want to be sure. 

If not, what kind of API you have in mind?

**Comment by Turbo87** [comment]
I was thinking more like this:

```
match(response, {
  id: Number,
  name: String,
});
```

**Comment by ozkxr** [comment]
Yes, I think it could work. 
I'm going to work on this.

**Comment by ozkxr** [comment]
It's done. It's already on npm: match-json@1.2.0.

If you find any bug or something, please don't hesitate on filing another issue or reopening this one.

Thanks!

**Comment by Turbo87** [comment]
awesome, thanks a lot!
