### ISSUE TITLE
Add support for partial matches

### ISSUE THREAD

**Issue by aquacash5** [ozkxr/match-json#6]
It would be nice if, this were capable of performing a partial match of the object.

Example:
```js
match({ name: 'Link', color: 'green' }, { name: 'Link' }) // => true
```

**Comment by ozkxr** [comment]
This makes sense to me. I will code this as soon as I can. (Probably tomorrow). Thanks!

**Comment by ozkxr** [comment]
I've been thinking about the API for partials and this is what I got:

First, I could implement match to work the way you state in your example.

```
match({ name: 'Link', color: 'green' }, { name: 'Link' }) // => true
```

And I think it looks great, but that comes with breaking changes.
Currently the result of that example is false.

And while I could make those API changes making a 2.0.0. I think the best option is to have both __regular__ and partial modes.

So this is how I think the API should work:

First, make an aditional argument to `match`: `partial`(boolean), so that way, the user have the option to use partial matches.

```
match({ name: 'Link', color: 'green' }, { name: 'Link' }, true) // => true
```

The same way for `bake`.

```
bake({ name: 'Link' }, true) // => true
```

Then, add an aditional `partial` function, which will be __sugar syntax__ with the partial mode predefined as default.

```
import { partial } from 'match-json';


partial({ name: 'Link', color: 'green' }, { name: 'Link' }) // => true
```

So, what do you think?

**Comment by aquacash5** [comment]
If you changing the API, I would suggest leaving the partial as a separate function.

From there would do one of two things.

### One

Change the match function to be individually exported. 

```js
const jsonMatch = require('match-json');

jsonMatch.match({ name: 'Link', color: 'green' }, { name: 'Link', color: 'green' });  // => true
```

This would allow people to do object unpacking when importing the module

```js
const {match} = require('match-json');

match({ name: 'Link', color: 'green' }, { name: 'Link', color: 'green' });  // => true
```

Then change the bake function to take a function then a pattern.
This will make it so you tell the bake function which kind of function you are *baking in*.

```js
const {match, partial, bake} = require('match-json');

const tingle = { name: 'Tingle', color:'green' };

const greenLinks = bake(match, { name: 'Link', color: 'green' });
const greens = bake(partial, { color: 'green' });

greenLinks(tingle)  // => false
greens(tingle)  // => true
```

### Two

Make partial a separate import.

```js
const partial = require('match-json/partial');

partial({ name: 'Link', color: 'green' }, { name: 'Link' });  // => true
```

This can then share the same interface as the match object.

```js
const partial = require('match-json/partial');

const links = partial.bake({ name: 'Link' });
links({ name: 'Link', color: 'green' });  // => true
links({ name: 'Link', color: 'red' });  // => true
```

**Comment by aquacash5** [comment]
Technically the second option doesn't change the API, It just extends it.

**Comment by ozkxr** [comment]
I think the second option is the way to go.

Do you think `partial` should affect the way arrays are matched too?


This way
```javascript 
partial(['git', 'hub'], ['git']) // => true??
```

I think `partial` should not affect arrays, but what do you think?

**Comment by aquacash5** [comment]
Sorry about the wait. I think that for partial it should match arrays exact.

**Comment by ozkxr** [comment]
I just published a new version with partial matches support on npm. It's on `match-json@1.3.0`.

To use it:

```javascript
import { partial } from 'match-json';
```

or

```javascript
const partial = require('match-json').partial;
```

If you have an issue with the update, another feature request or anything else related to `match-json`, please don't hesitate on oppening another issue. Thanks!
