### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by ghost** [ozkxr/match-json#9]
Hello. Thanks for the module. I have an issue, I tried to require with js file and import in mjs, cjs the same error: 

internal/modules/cjs/loader.js:1163
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:
Node version: 13.10.1
Shows this when I'm testing it:
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module"

**Comment by ozkxr** [comment]
Hello. Thanks for opening this issue.
I’ll work on that today.

**Comment by ozkxr** [comment]
I think it's fixed now. 
I just had to delete the `"type": "module"` I left in the `package.json`.

I just published `match-json` v1.3.2.
Please confirm if it's working for you so we can close this issue.

**Comment by ghost** [comment]
Yea, I can confirm it works now. Thanks for looking into it. Have a good day sir.
